# Generated by Django 5.2 on 2025-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_quote', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_quotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
            options={
                'db_table': 'days',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'recommendation_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('college_major', models.TextField(blank=True, null=True)),
                ('college_year', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('comfort_foods', models.TextField(blank=True, null=True)),
                ('music_taste', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellness_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellness_inputs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellness_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellness_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellness_scores',
                'managed': False,
            },
        ),
    ]
